configuration:
  projectName: gateway-ui
server:
  port: 80
zuul:
  routes:
    cats:
      url: http://192.168.1.51:9000
    dogs:
      url: http://192.168.1.51:9001
---
spring:
  profiles: development
server:
  port: 8080
zuul:
  routes:
    cats:
      url: http://localhost:9000
    dogs:
      url: http://localhost:9001