configuration:
  projectName: gateway-ui
server:
  port: 80
zuul:
  routes:
    cats:
      paths: /cats/**
      url: http://192.168.1.51:9000
---
spring:
  profiles: development
server:
  port: 8080
zuul:
  routes:
    cats:
      paths: /cats/**
      url: http://localhost:9000